version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: '05:00'
    allow:
      - dependency-type: production
